### ISSUE TITLE
naomi gd-rom and naomi 2

### ISSUE THREAD

**Issue by legluondunet** [anthonycaccese/alekfull-nx-es-de#3]
Hello,
I use emulationstation-de with alekfull-nx-es-de.
Concerning Naomi gd-rom, there is no background image right? 
And Naomi 2 theme section does not exist or I did something wrong?
Thank you for your help.

**Comment by anthonycaccese** [comment]
correct those images do not exist.  They will need to be created and submitted by the community and I will gladly add them.

**Comment by legluondunet** [comment]
Could you leave this report opened until community provides theme for this two consoles games?

**Comment by anthonycaccese** [comment]
I am glad to accept contributions from the community at any time.  I would like to only keep open items I am actively working on in this tracker.
