### ISSUE TITLE
Proposal to update art assets and apply consistency

### ISSUE THREAD

**Issue by vitamanic** [anthonycaccese/alekfull-nx-es-de#4]
Hi,

I want to preface this by letting you know that I'm aware you only ported this theme!

I'm a graphic designer, and while I like the overall idea of this theme, a lot of the elements are either inconsistent with each other, not aligned from system to system, missing, have errors, or are heavily compressed/low resolution.

That said, I'm milling over the idea to rework the art assets for myself while addressing the following problems:

- Use 4K quality art assets and apply them in a consistent manner for each system, fill in missing gaps for systems that lack them
- Fill in missing gaps in system logos and make them consistent (there's currently a mix of pictures and text)
- Rework the game list table to blend in with the rest of the graphical elements
- Develop a drag and drop Photoshop template to easily add future systems/additions to ES-DE
- On the system view, use a unique AND iconic character/scene that's accurate to the specific system it's representing
- Apply some level of newish, flatter design theory

I'm attaching two quick mockups that I made to illustrate my idea. Please note that I'm leaning toward only using logos in the carousel to avoid redundancy with the full logo/name in the background. I didn't think to do this before piecing together the mockup.

If you'd be interested in working with me to update this theme, I'd be happy to help!

<img width="1792" alt="Screenshot 2023-03-20 at 4 08 28 AM" src="https://user-images.githubusercontent.com/96499020/226281796-8fd02b80-6beb-4781-95c3-5363de736e47.png">

Alternative:
<img width="1792" alt="Screenshot 2023-03-20 at 4 32 02 AM" src="https://user-images.githubusercontent.com/96499020/226286353-895aa7f7-0b53-4ef5-b44a-d7e23e5db1b6.png">

**Comment by anthonycaccese** [comment]
Hi @vitamanic!  Thank you for writing and yes I am very interested in working with you on your proposed updates. 

re: "Please note that I'm leaning toward only using logos in the carousel to avoid redundancy with the full logo/name in the background"
- Yes I very much agree with this approach.   I had started a quick experiment of that with the background for Amiga (https://github.com/anthonycaccese/alekfull-nx-es-de/blob/main/_inc/images/systems/amiga-background.jpg) and liked that it removed the duplication of logos on system view and also felt it worked a bit better as a background on gamelist too.    

I also agree with the list of problems to solve as you have laid them out and I am glad to work on the code updates needed for those taking your lead on design elements and imagery.

If you have discord we can meet up through the ES-DE Server (my name there is antfortytwo) and start up a dm to work through specifics.  Let me know if that sounds good.

Thank you again for writing

**Comment by vitamanic** [comment]
Thanks for getting back to me @anthonycaccese, I'm happy you're interested!

I'm one of those weirdos that's stepped away from social media to alleviate issues with stress/anxiety, so unfortunately I don't use Discord. Is there any way we could do it over an email chain? It would be easier for me that way regardless since that's where most of my communications are for various projects/clients.

vitamin (at) fastmail (dot) com

Thanks!

**Comment by anthonycaccese** [comment]
I totally understand @vitamanic and will reach out to through email, that totally works for me too.
