### ISSUE TITLE
Super Game Boy background missing.

### ISSUE THREAD

**Issue by NatParable** [anthonycaccese/alekfull-nx-es-de#5]
As the title says, the background for the Super Game Boy is missing. This can be easily fixed by downloading the background from the original github, and saving it to the images folder as "sgb-background.jpg".

Original background: https://github.com/fagnerpc/Alekfull-NX/blob/master/assets/arts/sgb.jpg

**Comment by anthonycaccese** [comment]
Thank you!  This is added now.

**Comment by NatParable** [comment]
I hate to reopen this issue, but the backround has the wrong filename so it's not being used. It has to be named "sgb-background" for it to work.
