### ISSUE TITLE
Suggestion: Make Templates available for editing

### ISSUE THREAD

**Issue by aorin1** [anthonycaccese/alekfull-nx-es-de#6]
Hi! Do you have PSD templates so the user can add more systems and possibly edit existing ones? Mostly the main system backgrounds.
For instance, there's a Tomb Raider Level Editor, similar to DOOM and other source ports and also a system dedicated to hacks/homebrews, etc.
Thanks!

**Comment by anthonycaccese** [comment]
sorry I do not as I am not the original designer of this theme.  I simply ported the xml to be useable in ES-DE.  The original creator of the theme is https://github.com/fagnerpc/Alekfull-NX

**Comment by aorin1** [comment]
> sorry I do not as I am not the original designer of this theme. I simply ported the xml to be useable in ES-DE. The original creator of the theme is https://github.com/fagnerpc/Alekfull-NX

Thanks, I'll ask him and let you know, maybe the templates can be useful to you as well!

**Comment by aorin1** [comment]
Thanks, I'll ask him and let you know, maybe the templates can be useful to you as well!
