### ISSUE TITLE
Curious if you'd ever be willing to add the "S-Online" view?

### ISSUE THREAD

**Issue by Jambudd** [anthonycaccese/alekfull-nx-es-de#7]
Made a account to specifically ask. Currently i'm running the batocera version of his theme, and have absolutely fallen in love with the switch online view.

**Comment by anthonycaccese** [comment]
thank you for writing - may you provide an example?  I am not totally following which view you are referring to.

**Comment by anthonycaccese** [comment]
closing for now, if you have an example to provide in the future just reply here.
