### ISSUE TITLE
Version compatible with Retropie

### ISSUE THREAD

**Issue by oxygen79** [anthonycaccese/alekfull-nx-es-de#8]
Hi, is it compatible with raspberry(retropie) ? On Google I find traces of a compatible version of yours, but it is no longer available. Would it be possible to have that template? Thank you

**Comment by anthonycaccese** [comment]
sorry this version is only built for ES-DE, so it will not work on retropie.  I had done a quick port for retropie but needed to archive it and no longer maintain it (I had many other themes to work on) so someone else would need to pick that up and finish the work to make it work on retropie.
